# Generated by Django 5.2 on 2025-06-30 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bed',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorms.room'),
        ),
    ]
