# Generated by Django 5.2 on 2025-07-14 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_bed_booking_room'),
        ('dorms', '0002_room_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorms.bed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookingHistory',
        ),
    ]
