# Generated by Django 5.2 on 2025-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bed_booking_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2023-02-01'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2023-02-01'),
        ),
    ]
