# Generated by Django 5.2 on 2025-07-19 21:37

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=django_jalali.db.models.jDateField(default='2023-02-01'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=django_jalali.db.models.jDateField(default='2023-02-01'),
        ),
    ]
