# Generated by Django 5.2 on 2025-07-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_created_at_alter_booking_end_date_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(blank=True, choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'IDPay'), ('payir', 'Pay.ir')], help_text='درگاه پرداخت انتخابی', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, help_text='کد پیگیری پرداخت موفق', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='مبلغ به تومان'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
