# Generated by Django 5.2 on 2025-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0002_room_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
