# Generated by Django 5.2 on 2025-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0003_alter_bed_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='قیمت ماهانه به تومان'),
        ),
    ]
